# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2020-12-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributor',
            old_name='isreadgift',
            new_name='isreadcontrib',
        ),
        migrations.AddField(
            model_name='contributor',
            name='isreadreceiver',
            field=models.BooleanField(default=False),
        ),
    ]
