# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-01 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0004_type_of_notification_notif_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type_of_notification',
            old_name='notif_message',
            new_name='notif_header_message',
        ),
    ]
