# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-01 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0005_auto_20210101_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_of_notification',
            name='notif_main_message',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
