# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-05 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0006_type_of_notification_notif_main_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type_of_notification',
            name='notif_header_message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='type_of_notification',
            name='notif_main_message',
            field=models.TextField(blank=True),
        ),
    ]
