# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0008_auto_20210105_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notif_header_message',
            field=models.TextField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='notifications',
            name='notif_main_message',
            field=models.TextField(blank=True, default=False),
        ),
    ]
