# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-06 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0009_auto_20210106_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='notif_header_message',
        ),
        migrations.AddField(
            model_name='type_of_notification',
            name='no_of_arguments',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
