# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-06 21:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0010_auto_20210106_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notif_main_message',
            new_name='arguments',
        ),
    ]
