# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2021-01-08 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slambook', '0011_auto_20210106_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='cquestion',
            name='typ',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
